apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: aggregate-analytics
spec:
  template:
    metadata:
      name:  aggregate-analytics-v1
      annotations:
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
        - image: docker.io/aslom/aggregate-analytics:v1
          env:
            - name: MESSAGE
              value: " - Handled by aggregate-analytics"
