apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: send-alert
spec:
  template:
    spec:
      containers:
      - image: aslom/send-alert-to-slack
        env:
        - name: SLACK_INCOMING_WEBHOOK_URL
          value: https://hooks.slack.com/services
