apiVersion: flows.knative.dev/v1beta1
kind: Sequence
metadata:
  name: sequence-audit
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: KafkaChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: aggregate-analytics
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: send-alert
