apiVersion: flows.knative.dev/v1beta1
kind: Sequence
metadata:
  name: summary-analyics-alert-pipeline
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1beta1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: event-display
  reply:
    ref:
      kind: Service
      apiVersion: serving.knative.dev/v1
      name: event-display
