cat 100-aggregate-analytics.yaml
echo "---"
cat 201-analytics-sequence.yaml
echo "---"
cat 302-analytics-parallel.yaml
echo "---"
cat 400-event-supported-analytics-v1-filter.yaml
echo "---"
cat 402-router-parallel.yaml
#echo "---"
#cat 411-router-sequence.yaml
echo "---"
cat 500-loan-app-sequence.yaml
